apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "daliuge.fullname" . }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "daliuge.labels" . | indent 4 }}
spec:
  completions: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "daliuge.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.dlg.container }}:{{ .Values.dlg.version }}
        imagePullPolicy: {{ .Values.dlg.imagePullPolicy }}
        name: dlg-dim
        command: ["dlg", "dim", "-H", "0.0.0.0", "-vv", "-N", "127.0.0.1"]
        {{- with .Values.dlg_dim.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      - image: {{ .Values.dlg.container }}:{{ .Values.dlg.version }}
        imagePullPolicy: {{ .Values.dlg.imagePullPolicy }}
        name: dlg-nm
        command: ["dlg", "nm", "-vv"]
        {{- with .Values.dlg_nm.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "daliuge.fullname" . }}-dlg-dim
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ include "daliuge.name" . }}
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
