apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dask.fullname" . }}-worker
  labels:
    app: {{ template "dask.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "dask.chart" . }}
    component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ template "dask.name" . }}
      release: {{ .Release.Name | quote }}
      component: worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "dask.name" . }}
        release: {{ .Release.Name | quote }}
        component: worker
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- if or .Values.buffers .Values.secrets }}
      volumes:
        {{- range $buffer := .Values.buffers }}
        - name: {{ $buffer }}
          persistentVolumeClaim:
            claimName: {{ $buffer }}
        {{- end }}
        {{- range $secret := .Values.secrets }}
        - name: {{ $secret }}
          secret:
            secretName: {{ $secret }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ template "dask.fullname" . }}-worker
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - python3
          args:
            - -m
            - distributed.cli.dask_worker
            - {{ template "dask.fullname" . }}-scheduler:{{ .Values.scheduler.servicePort }}
          {{- if .Values.worker.resources.limits }}
            - --nthreads
            - {{ .Values.worker.resources.limits.cpu | default .Values.worker.default_resources.cpu | quote }}
            - --memory-limit
            - {{ .Values.worker.resources.limits.memory | default .Values.worker.default_resources.memory | quote }}
          {{- end }}
            - --no-dashboard
          {{- if .Values.worker.port }}
            - --worker-port
            - {{ .Values.worker.port | quote }}
          {{- end }}
          ports:
            - containerPort: 8789
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          env:
            {{- toYaml .Values.worker.env | nindent 12 }}
          {{- if or .Values.buffers .Values.secrets }}
          volumeMounts:
            {{- range $buffer := .Values.buffers }}
            - mountPath: /buffer/{{ $buffer }}
              name: {{ $buffer }}
            {{- end }}
            {{- range $secret := .Values.secrets }}
            - mountPath: /secret/{{ $secret }}
              name: {{ $secret }}
            {{- end }}
          {{- end }}
    {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
