receiver:
        completions: 1
        image: nexus.engageska-portugal.pt/ska-telescope/pss-docker-centos-dev:1.0.0
        imagePullPolicy: IfNotPresent
        containerPort: 9021
        protocol: UDP

service:
        port: 9021

sender:
        image: pulsarben/pss2sdp-send
        completions: 1
        imagePullPolicy: Always

