apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "create-buffer.labels" . | indent 4 }}
spec:
  storageClassName: {{ .Values.class }}
  accessModes:
    {{ toYaml .Values.accessModes }}
  resources:
    requests:
      storage: {{ .Values.size }}
