---
# Dummy Service to ensure Pod is DNS addressable
apiVersion: v1
kind: Service
metadata:
  name: receive
  namespace: {{ .Release.Namespace }}
  labels:
    workflow: {{ .Values.workflow }}
spec:
  clusterIP: None
  selector:
    workflow: {{ .Values.workflow }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name | default (include "receive.fullname" .) | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    workflow: {{ .Values.workflow }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      workflow: {{ .Values.workflow }}
  serviceName: receive
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "receive.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        workflow: {{ .Values.workflow }}
    spec:
      {{- if .Values.initContainersEnabled }}
      initContainers:
{{ toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      containers:
      - name: receiver
        image: {{ .Values.image }}:{{ .Values.version }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        volumeMounts:
          - name: "{{ $.Values.pvc.name }}"
            mountPath: "{{ $.Values.pvc.path }}"
            {{- if .Values.extraVolumeMountsEnabled }}
            {{- toYaml .Values.extraVolumeMounts | nindent 6 }}
            {{- end }}
        {{- if .Values.commandEnabled }}
        command: [
        {{- range .Values.arguments }}
        {{ . }}
        {{ end }}
        ]
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.extraContainersEnabled }}
        {{- toYaml .Values.extraContainers | nindent 6 }}
        {{- end }}
      volumes:
        - name: "{{ $.Values.pvc.name }}"
          persistentVolumeClaim:
            claimName: "{{ $.Values.pvc.name }}"
          {{- if .Values.extraVolumesEnabled }}
          {{- toYaml .Values.extraVolumes | nindent 6 }}
          {{- end }}

