---
# Dummy Service to ensure Pod is DNS addressable
apiVersion: v1
kind: Service
metadata:
  name: receive
  namespace: {{ .Release.Namespace }}
  labels:
    workflow: {{ .Values.service.workflow }}
spec:
  clusterIP: None
  selector:
    workflow: {{ .Values.service.workflow }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "receive.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    workflow: {{ .Values.workflow }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      workflow: {{ .Values.workflow }}
  serviceName: receive
  template:
    metadata:
      labels:
        workflow: {{ .Values.workflow }}
    spec:
      containers:
      - name: receive
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 8 }}
        command: {{ .Values.command }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.extraContainersEnabled }}
        {{- toYaml .Values.extraContainers | nindent 6 }}
        {{- end }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}