---
# Dummy Service to ensure Pod is DNS addressable
apiVersion: v1
kind: Service
metadata:
  name: {{ template "receive.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    workflow: {{ .Values.service.workflow }}
spec:
  clusterIP: None
  selector:
    workflow: {{ .Values.service.workflow }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "receive.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    workflow: {{ .Values.workflow }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      workflow: {{ .Values.workflow }}
  serviceName: {{ template "receive.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "receive.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        workflow: {{ .Values.workflow }}
    spec:
      {{- if .Values.initContainersEnabled }}
      initContainers:
{{ toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      containers:
      - name: receiver
        image: {{ .Values.image }}:{{ .Values.version }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 8 }}
        command: {{ toJson .Values.command }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.extraContainersEnabled }}
        {{- toYaml .Values.extraContainers | nindent 6 }}
        {{- end }}
      volumes:
{{ toYaml .Values.volumes | nindent 8 }}
