---
# Dummy Service to ensure Pod is DNS addressable
apiVersion: v1
kind: Service
metadata:
  name: receive
  namespace: {{ .Release.Namespace }}
  labels:
    workflow: {{ .Values.service.workflow }}
spec:
  clusterIP: None
  selector:
    workflow: {{ .Values.service.workflow }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: receive
  namespace: {{ .Release.Namespace }}
  labels:
    workflow: {{ .Values.receive.workflow }}
spec:
  replicas: {{ .Values.receive.replicas }}
  selector:
    matchLabels:
      workflow: {{ .Values.receive.workflow }}
  serviceName: receive
  template:
    metadata:
      labels:
        workflow: {{ .Values.receive.workflow }}
    spec:
      containers:
      - name: receive
        image: {{ .Values.receive.image }}
        imagePullPolicy: {{ .Values.receive.imagePullPolicy }}
        volumeMounts:
          - mountPath: {{ .Values.volume.path }}
            name: {{ .Values.volume.name }}
        command: {{ .Values.receive.command }}
        {{- with .Values.receive.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.volumeClaim.name }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.volumeClaim.storage }}