apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cbf_sdp_emulator.fullname" . }}-send-recv
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cbf_sdp_emulator.labels" . | indent 4 }}
spec:
  completions: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cbf_sdp_emulator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: {{ .Values.cbf_sdp_emulator.restartPolicy }}
      containers:
      - image: {{ .Values.cbf_sdp_emulator.container }}:{{ .Values.cbf_sdp_emulator.version }}
        imagePullPolicy: {{ .Values.cbf_sdp_emulator.imagePullPolicy }}
        name: multicast-receiver-1
        command: ["emu-recv", "-o", "transmission.channels_per_stream=4", "-o", "reception.datamodel=/input.ms", "-o", "reception.outputfilename=/tmp/output.ms", "-o", "reception.bind_hostname=239.0.0.1"]
        volumeMounts:
        - mountPath: /input.ms
          name: input-ms-volume
        {{- with .Values.receivers.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      - image: {{ .Values.cbf_sdp_emulator.container }}:{{ .Values.cbf_sdp_emulator.version }}
        imagePullPolicy: {{ .Values.cbf_sdp_emulator.imagePullPolicy }}
        name: multicast-receiver-2
        command: ["emu-recv", "-o", "transmission.channels_per_stream=4", "-o", "reception.datamodel=/input.ms", "-o", "reception.outputfilename=/tmp/output.ms", "-o", "reception.bind_hostname=239.0.0.1"]
        volumeMounts:
        - mountPath: /input.ms
          name: input-ms-volume
        {{- with .Values.receivers.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      - image: {{ .Values.cbf_sdp_emulator.container }}:{{ .Values.cbf_sdp_emulator.version }}
        imagePullPolicy: {{ .Values.cbf_sdp_emulator.imagePullPolicy }}
        name: sender
        command: ["emu-send", "/input.ms", "-o", "transmission.channels_per_stream=4", "-o", "transmission.rate=147000", "-o", "transmission.target_host=239.0.0.1"]
        volumeMounts:
        - mountPath: /input.ms
          name: input-ms-volume
        {{- with .Values.sender.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: input-ms-volume
        {{ .Values.input.mountType }}:
        {{- with .Values.input.mountTypeOptions }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
  backoffLimit: 1
