# Default values for receive
# Declare variables to be passed into your templates.

workflow: receive
name: ""
image: ""
version: ""
imagePullPolicy: IfNotPresent
replicas: 1
resources: {}

commandEnabled: true
command: [
    "{{ .Values.recv_emu }}",
    "-o",
    "transmission.channels_per_stream={{ .Values.transmission.channels_per_stream}}",
    "-o",
    "transmission.rate={{ .Values.transmission.rate}}",
    "-o",
    "reception.num_ports={{ .Values.reception.num_ports }}",
    "-o",
    "reception.receiver_port_start={{ .Values.reception.receiver_port_start }}",
    "-o",
    "reception.datamodel=/mnt/data/{{ .Values.model.name }}",
    "-o",
    "reception.outputfilename=/mnt/data/{{ .Values.reception.outputfilename }}",
    "-o",
    "payload.method={{ .Values.payload.method }}",
    "-o",
    "reader.num_chan={{ .Values.reader.num_chan }}",
    "-o",
    "reader.num_repeats={{ .Values.reader.num_repeats }}",
    "-o",
    "reader.num_timestamps={{ .Values.reader.num_timestamps }}",
    "-o",
    "reader.start_chan={{ .Values.reader.start_chan }}"
]

initContainersEnabled: false
extraContainersEnabled: false
extraVolumesEnabled: false
extraVolumeMountsEnabled: false

initContainers: []
extraContainers: []
extraVolumes: []
extraVolumeMounts: []

nameOverride: ""
fullnameOverride: ""
