# Default values for receive
# Declare variables to be passed into your templates.


service:
  workflow: cbf-receiver


receive:
  workflow: cbf-receiver
  completions: 1
  image: k8s.gcr.io/nginx-slim:0.8
  imagePullPolicy: IfNotPresent
  replicas: 1
  ttl: 3600
  command: []
  resources: {}

volume:
  name: www
  path: /usr/share/nginx/html

volumeClaim:
  name: www
  storage: 1Gi

nameOverride: ""
fullnameOverride: ""

